runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: jinja2
    version: latest
  - name: instagram_explore
    version: latest

handlers:
  - url: /.*
    script: main.app
  - url: try2.py
    script: try2.app
